Name:           mpvpaper
Version:        1.8.0
Release:        1%{?dist}
Summary:        Video wallpaper player using mpv for wlroots-based Wayland compositors

License:        GPLv3+
URL:            https://github.com/GhostNaN/mpvpaper
# Source tarball is generated by Copr from the git repository.
# For manual build: cd mpvpaper-rust && git archive --prefix=mpvpaper-1.8.0/ HEAD | gzip > mpvpaper-1.8.0.tar.gz
Source0:        mpvpaper-%{version}.tar.gz

BuildRequires:  cargo
BuildRequires:  rust
BuildRequires:  pkgconfig(wayland-client)
BuildRequires:  pkgconfig(wayland-egl)
BuildRequires:  pkgconfig(mpv)

Requires:       mesa-libEGL
Requires:       mpv-libs
Requires:       wayland

%description
mpvpaper is a video wallpaper program for wlroots-based Wayland compositors
(such as Sway, Hyprland, river). It plays videos via mpv and renders them
as your desktop wallpaper through the wlr-layer-shell protocol.

This is a complete Rust rewrite of the original C mpvpaper, offering:
- Type-safe Wayland/EGL/mpv bindings via Rust crates
- Memory safety through Rust's ownership system
- Thread safety checked at compile time
- Event-driven rendering via eventfd (no busy-waiting)
- Direct /proc scanning instead of subprocess spawning

%prep
%setup -q -n %{name}-%{version}

%build
export RUSTFLAGS="-C opt-level=3 -C debuginfo=1"
cargo build --release %{?_smp_mflags}

%install
install -D -m 0755 target/release/mpvpaper %{buildroot}%{_bindir}/mpvpaper
install -D -m 0755 target/release/mpvpaper-holder %{buildroot}%{_bindir}/mpvpaper-holder

%files
%{_bindir}/mpvpaper
%{_bindir}/mpvpaper-holder
%doc README.md
%license LICENSE

%changelog
* Wed Jun 17 2026 TurkeyC <u202413051@hust.edu.cn> - 1.8.0-1
- Initial Copr build for Fedora 43+
- Rust rewrite of mpvpaper
